spring:
  profiles:
    active: @spring.profiles.active@
    
    
mybatis:
  config-location: classpath:mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: springboot.yang.springboot.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml  
  
spring:
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: ${datasource.url}         # 数据库名称
    username: admin
    password: admin
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间    


  